# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-19 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repostiroy', '0002_auto_20170919_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disk',
            name='model',
            field=models.CharField(max_length=64, verbose_name='磁盘型号'),
        ),
    ]
